import type { Question } from './types';

export const movieChapterTitle = '经典港片场景粤语句子挑战';

export const movieQuestions: Question[] = [
  {
    id: 1,
    prompt: '听/读这句：“阿 sir，唔好意思，我真系赶时间。”这句话最可能表达什么？',
    cantoneseText: '阿 sir，唔好意思，我真系赶时间。',
    choices: ['礼貌解释自己很赶', '邀请警察喝茶', '抱怨时间太慢', '说自己不用走'],
    answerIndex: 0,
    explanation: '“唔好意思”是抱歉/打扰，“真系赶时间”是确实很赶。整句是紧张但礼貌的解释。',
    theme: '警匪街口',
    difficulty: '进阶',
    questionType: 'meaning',
    skillTag: '句意理解',
    pronunciationHint: 'm4 hou2 ji3 si1, zan1 hai6 gon2 si4 gaan3'
  },
  {
    id: 2,
    prompt: '茶餐厅伙计说：“冻柠茶少甜，唔该晒。”最适合的场景是哪一个？',
    cantoneseText: '冻柠茶少甜，唔该晒。',
    choices: ['点饮品', '追车', '谈判', '告别'],
    answerIndex: 0,
    explanation: '“冻柠茶少甜”是港式茶餐厅常见点单方式，“唔该晒”是很客气的谢谢。',
    theme: '茶餐厅点单',
    difficulty: '进阶',
    questionType: 'scene',
    skillTag: '场景推断',
    pronunciationHint: 'dung3 ling4 caa4 siu2 tim4, m4 goi1 saai3'
  },
  {
    id: 3,
    prompt: '“你唔好扮晒嘢啦”里的语气更接近？',
    cantoneseText: '你唔好扮晒嘢啦。',
    choices: ['吐槽对方别装', '鼓励对方继续', '认真道歉', '问对方去哪'],
    answerIndex: 0,
    explanation: '“扮晒嘢”有“装模作样”的感觉，这句多半是在吐槽、拆穿。',
    theme: '喜剧误会',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '语气判断',
    pronunciationHint: 'nei5 m4 hou2 baan6 saai3 je5 laa1'
  },
  {
    id: 4,
    prompt: '补全句子：“呢度人多，____讲。”',
    cantoneseText: '呢度人多，细声啲讲。',
    choices: ['细声啲', '快手啲', '行远啲', '贵少少'],
    answerIndex: 0,
    explanation: '人多时怕别人听见，最自然是“细声啲讲”，也就是“小声一点说”。',
    theme: '街头密谈',
    difficulty: '进阶',
    questionType: 'missingPhrase',
    skillTag: '句子补全',
    pronunciationHint: 'ni1 dou6 jan4 do1, sai3 seng1 di1 gong2'
  },
  {
    id: 5,
    prompt: '先听这句：“你而家先嚟讲，会唔会迟咗啲？”它在质疑什么？',
    cantoneseText: '你而家先嚟讲，会唔会迟咗啲？',
    choices: ['现在才说太晚了', '你说得太小声', '你来得太早', '你讲得很漂亮'],
    answerIndex: 0,
    explanation: '“而家先嚟讲”是现在才来说，“迟咗啲”是晚了一点，整体是质疑时机太迟。',
    theme: '兄弟摊牌',
    difficulty: '挑战',
    questionType: 'listenFirst',
    skillTag: '听辨理解',
    pronunciationHint: 'nei5 ji4 gaa1 sin1 lai4 gong2, wui5 m4 wui5 ci4 zo2 di1'
  },
  {
    id: 6,
    prompt: '“我冇呃你，真系冇。”这句话的重点是什么？',
    cantoneseText: '我冇呃你，真系冇。',
    choices: ['强调自己没有骗你', '说自己没有钱', '表示自己不认识你', '问你有没有空'],
    answerIndex: 0,
    explanation: '“呃”是骗，“真系冇”是确实没有。句子是在强调清白。',
    theme: '审问房间',
    difficulty: '进阶',
    questionType: 'meaning',
    skillTag: '句意理解',
    pronunciationHint: 'ngo5 mou5 aak1 nei5, zan1 hai6 mou5'
  },
  {
    id: 7,
    prompt: '“咪住，等我谂清楚先。”说话人想做什么？',
    cantoneseText: '咪住，等我谂清楚先。',
    choices: ['暂停一下再想清楚', '马上冲出去', '请人买单', '已经决定好了'],
    answerIndex: 0,
    explanation: '“咪住”是先别/等一下，“谂清楚”是想清楚，“先”表示先做这件事。',
    theme: '临门决定',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '句意理解',
    pronunciationHint: 'mai5 zyu6, dang2 ngo5 nam2 cing1 co2 sin1'
  },
  {
    id: 8,
    prompt: '“你讲到咁大声，成条街都听到。”里面“成条街”强调什么？',
    cantoneseText: '你讲到咁大声，成条街都听到。',
    choices: ['声音大到很多人都听见', '街道真的变长了', '只有街尾听见', '对方唱歌很好'],
    answerIndex: 0,
    explanation: '“成条街”是夸张地说整条街，“都听到”表示全都听见。',
    theme: '街边争执',
    difficulty: '进阶',
    questionType: 'tone',
    skillTag: '夸张语气',
    pronunciationHint: 'nei5 gong2 dou3 gam3 daai6 seng1, seng4 tiu4 gaai1 dou1 teng1 dou2'
  },
  {
    id: 9,
    prompt: '“唔系我唔帮你，系而家真系冇办法。”最准确的理解是？',
    cantoneseText: '唔系我唔帮你，系而家真系冇办法。',
    choices: ['不是不帮，而是现在没办法', '我从来不会帮你', '现在办法很多', '你不用别人帮'],
    answerIndex: 0,
    explanation: '“唔系…系…”是“不是…而是…”。这句是在解释限制，不是拒绝情义。',
    theme: '江湖两难',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '句式理解',
    pronunciationHint: 'm4 hai6 ngo5 m4 bong1 nei5, hai6 ji4 gaa1 zan1 hai6 mou5 baan6 faat3'
  },
  {
    id: 10,
    prompt: '“得啦得啦，我知你叻。”这句常见语气更像？',
    cantoneseText: '得啦得啦，我知你叻。',
    choices: ['有点敷衍或调侃', '非常正式表扬', '严肃命令撤退', '低声求救'],
    answerIndex: 0,
    explanation: '重复“得啦得啦”常有“好了好了”的感觉，“我知你叻”可真夸，也可带调侃。',
    theme: '喜剧拌嘴',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '语气判断',
    pronunciationHint: 'dak1 laa1 dak1 laa1, ngo5 zi1 nei5 lek1'
  },
  {
    id: 11,
    prompt: '补全句子：“有咩事，____先讲。”',
    cantoneseText: '有咩事，返去先讲。',
    choices: ['返去', '贵啲', '靓晒', '几多'],
    answerIndex: 0,
    explanation: '“返去先讲”是“回去再说/先回去再讲”，常用于不想在现场说清楚。',
    theme: '避开现场',
    difficulty: '进阶',
    questionType: 'missingPhrase',
    skillTag: '场景表达',
    pronunciationHint: 'jau5 me1 si6, faan1 heoi3 sin1 gong2'
  },
  {
    id: 12,
    prompt: '“你唔使惊，我喺度。”最适合表达哪种关系/情绪？',
    cantoneseText: '你唔使惊，我喺度。',
    choices: ['安慰和保护', '催促买单', '嘲笑别人', '表示很生气'],
    answerIndex: 0,
    explanation: '“唔使惊”是不用怕，“我喺度”是我在这里，是很典型的安慰句。',
    theme: '雨夜安慰',
    difficulty: '进阶',
    questionType: 'tone',
    skillTag: '情绪识别',
    pronunciationHint: 'nei5 m4 sai2 geng1, ngo5 hai2 dou6'
  },
  {
    id: 13,
    prompt: '“你走先，我搞掂呢度。”说话人是什么意思？',
    cantoneseText: '你走先，我搞掂呢度。',
    choices: ['让对方先走，自己处理这里', '叫对方一起留下', '说这里已经关门', '表示自己迷路'],
    answerIndex: 0,
    explanation: '“搞掂”是处理好、解决。“你走先”是你先走。',
    theme: '巷口分别',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '句意理解',
    pronunciationHint: 'nei5 zau2 sin1, ngo5 gaau2 dim6 ni1 dou6'
  },
  {
    id: 14,
    prompt: '“呢件事唔简单，唔好乱嚟。”里面“乱嚟”是什么意思？',
    cantoneseText: '呢件事唔简单，唔好乱嚟。',
    choices: ['不要乱来', '不要迟到', '不要唱歌', '不要太贵'],
    answerIndex: 0,
    explanation: '“乱嚟”就是乱来、草率行动。这句是在提醒谨慎。',
    theme: '调查线索',
    difficulty: '进阶',
    questionType: 'meaning',
    skillTag: '行动判断',
    pronunciationHint: 'ni1 gin6 si6 m4 gaan2 daan1, m4 hou2 lyun6 lai4'
  },
  {
    id: 15,
    prompt: '“你估我真系唔知咩？”这句的潜台词是？',
    cantoneseText: '你估我真系唔知咩？',
    choices: ['我其实知道', '我完全听不见', '我想问价格', '我需要睡觉'],
    answerIndex: 0,
    explanation: '“你估…咩？”是反问语气，这里不是不知道，而是在说“我难道不知道吗”。',
    theme: '反问拆穿',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '反问语气',
    pronunciationHint: 'nei5 gu2 ngo5 zan1 hai6 m4 zi1 me1'
  },
  {
    id: 16,
    prompt: '先听这句：“讲真，今次我真系有啲嬲。”说话人的情绪是？',
    cantoneseText: '讲真，今次我真系有啲嬲。',
    choices: ['有点生气', '特别开心', '很想点餐', '完全不在意'],
    answerIndex: 0,
    explanation: '“讲真”是说真的，“嬲”是生气，“有啲”是一点点。',
    theme: '朋友摊开讲',
    difficulty: '挑战',
    questionType: 'listenFirst',
    skillTag: '情绪听辨',
    pronunciationHint: 'gong2 zan1, gam1 ci3 ngo5 zan1 hai6 jau5 di1 nau1'
  },
  {
    id: 17,
    prompt: '“大家自己人，唔使讲到咁绝。”最自然的理解是？',
    cantoneseText: '大家自己人，唔使讲到咁绝。',
    choices: ['都是自己人，别把话说太绝', '大家都不认识', '必须马上离开', '说话要更大声'],
    answerIndex: 0,
    explanation: '“自己人”是同一边/熟人，“讲到咁绝”是话说得太绝。',
    theme: '和解劝说',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '关系判断',
    pronunciationHint: 'daai6 gaa1 zi6 gei2 jan4, m4 sai2 gong2 dou3 gam3 zyut6'
  },
  {
    id: 18,
    prompt: '补全句子：“唔该，____，我想问路。”',
    cantoneseText: '唔该，借借，我想问路。',
    choices: ['借借', '嬲嬲', '晒晒', '掂掂'],
    answerIndex: 0,
    explanation: '“借借”常用于请别人让一让、借过一下。这里是礼貌开口。',
    theme: '街头问路',
    difficulty: '进阶',
    questionType: 'missingPhrase',
    skillTag: '礼貌表达',
    pronunciationHint: 'm4 goi1, ze3 ze3, ngo5 soeng2 man6 lou6'
  },
  {
    id: 19,
    prompt: '“你咁样讲，我好难落台。”这里“落台”更接近？',
    cantoneseText: '你咁样讲，我好难落台。',
    choices: ['下不来台/难堪', '从舞台走下来', '去楼下吃饭', '放下麦克风'],
    answerIndex: 0,
    explanation: '“落台”可字面下台，也常引申为“下台阶”。这句是在说让人难堪。',
    theme: '当众尴尬',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '引申义',
    pronunciationHint: 'nei5 gam2 joeng2 gong2, ngo5 hou2 naan4 lok6 toi4'
  },
  {
    id: 20,
    prompt: '“算啦，今晚到呢度。”这句最像什么时刻？',
    cantoneseText: '算啦，今晚到呢度。',
    choices: ['收场/告一段落', '刚刚开场', '准备点餐', '要求加速'],
    answerIndex: 0,
    explanation: '“算啦”是算了，“到呢度”是到这里。整体是在收束、结束这一晚。',
    theme: '夜街收场',
    difficulty: '进阶',
    questionType: 'scene',
    skillTag: '场景推断',
    pronunciationHint: 'syun3 laa1, gam1 maan5 dou3 ni1 dou6'
  }
];
