import type { Question } from './types';

export const movieAdvancedChapterTitle = '港片常用场景进阶挑战';

export const movieAdvancedQuestions: Question[] = [
  {
    id: 1,
    prompt: '“你咁讲即系唔畀面啫。”最准确的潜台词是？',
    cantoneseText: '你咁讲即系唔畀面啫。',
    choices: ['你这样说让我下不来台', '你说得很有道理', '你是在帮我圆场', '你只是声音太小'],
    answerIndex: 0,
    explanation: '“畀面”是给面子，“唔畀面”不是单纯不同意，而是让对方难堪、失面子。',
    theme: '饭局保面',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '潜台词',
    pronunciationHint: 'nei5 gam2 gong2 zik1 hai6 m4 bei2 min6 ze1'
  },
  {
    id: 2,
    prompt: '“我唔系要赢，我系想讲清楚。”这句话最像在做什么？',
    cantoneseText: '我唔系要赢，我系想讲清楚。',
    choices: ['缓和争执并解释立场', '炫耀自己已经赢了', '要求对方立刻道歉', '表示自己不想再说'],
    answerIndex: 0,
    explanation: '“唔系…系…”是在纠正对方理解。重点不是赢，而是把事情说清楚。',
    theme: '兄弟争执',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '转折句式',
    pronunciationHint: 'ngo5 m4 hai6 jiu3 jeng4, ngo5 hai6 soeng2 gong2 cing1 co2'
  },
  {
    id: 3,
    prompt: '“呢件事你当冇发生过，好唔好？”最符合哪种场景？',
    cantoneseText: '呢件事你当冇发生过，好唔好？',
    choices: ['请求对方不要再追究', '邀请对方庆祝成功', '提醒对方记清楚细节', '要求对方公开说明'],
    answerIndex: 0,
    explanation: '“当冇发生过”是希望对方放下或保密，不是提醒记住。',
    theme: '秘密收口',
    difficulty: '挑战',
    questionType: 'scene',
    skillTag: '场景推断',
    pronunciationHint: 'ni1 gin6 si6 nei5 dong3 mou5 faat3 sang1 gwo3, hou2 m4 hou2'
  },
  {
    id: 4,
    prompt: '“你而家走，之后就唔好返嚟搵我。”语气最接近？',
    cantoneseText: '你而家走，之后就唔好返嚟搵我。',
    choices: ['带威胁感的最后通牒', '很轻松的告别', '普通问路', '礼貌邀请再来'],
    answerIndex: 0,
    explanation: '“之后就唔好…”是强硬边界，不是普通告别。',
    theme: '门口决裂',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '语气判断',
    pronunciationHint: 'nei5 ji4 gaa1 zau2, zi1 hau6 zau6 m4 hou2 faan1 lai4 wan2 ngo5'
  },
  {
    id: 5,
    prompt: '“大家都系出来做嘢，唔使去到咁尽。”说话人想表达什么？',
    cantoneseText: '大家都系出来做嘢，唔使去到咁尽。',
    choices: ['做事留点余地', '必须彻底追到底', '大家都不用工作', '这件事很简单'],
    answerIndex: 0,
    explanation: '“去到咁尽”是做到太绝、太狠。整句是在劝对方别逼太紧。',
    theme: '讲数留路',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '场面话',
    pronunciationHint: 'daai6 gaa1 dou1 hai6 ceot1 lai4 zou6 je5, m4 sai2 heoi3 dou3 gam3 zeon6'
  },
  {
    id: 6,
    prompt: '“你讲就容易，做落先知难。”这句在反驳什么？',
    cantoneseText: '你讲就容易，做落先知难。',
    choices: ['对方低估了执行难度', '对方已经做得很好', '这件事不用开始', '说话比行动更重要'],
    answerIndex: 0,
    explanation: '“做落”是做起来、实际做的时候。重点是现实执行比嘴上说难。',
    theme: '行动前争论',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '现实反驳',
    pronunciationHint: 'nei5 gong2 zau6 jung4 ji6, zou6 lok6 sin1 zi1 naan4'
  },
  {
    id: 7,
    prompt: '补全句子：“唔好再兜圈，____讲。”',
    cantoneseText: '唔好再兜圈，直接讲。',
    choices: ['直接', '慢慢', '客气', '细声'],
    answerIndex: 0,
    explanation: '“兜圈”是绕来绕去。相对的自然表达是“直接讲”。',
    theme: '逼问重点',
    difficulty: '挑战',
    questionType: 'missingPhrase',
    skillTag: '表达补全',
    pronunciationHint: 'm4 hou2 zoi3 dau1 hyun1, zik6 zip3 gong2'
  },
  {
    id: 8,
    prompt: '“我畀机会你讲，你唔好又话我冇听。”最像哪种心理？',
    cantoneseText: '我畀机会你讲，你唔好又话我冇听。',
    choices: ['先把话说在前面，避免被反咬', '真心邀请对方唱歌', '承认自己完全没听', '表示现在不准对方说话'],
    answerIndex: 0,
    explanation: '“你唔好又话…”是在预防对方之后指责自己，语气里有防备。',
    theme: '摊牌前奏',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '防备语气',
    pronunciationHint: 'ngo5 bei2 gei1 wui6 nei5 gong2, nei5 m4 hou2 jau6 waa6 ngo5 mou5 teng1'
  },
  {
    id: 9,
    prompt: '“呢啲说话，留返你自己听啦。”这句话通常不是在？',
    cantoneseText: '呢啲说话，留返你自己听啦。',
    choices: ['真诚接受解释', '拒绝听借口', '表达不耐烦', '切断对话'],
    answerIndex: 0,
    explanation: '这句带明显不耐烦：这些话留给你自己听吧。不是接受解释。',
    theme: '拒听借口',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '反向选择',
    pronunciationHint: 'ni1 di1 syut3 waa6, lau4 faan1 nei5 zi6 gei2 teng1 laa1'
  },
  {
    id: 10,
    prompt: '“我帮你，唔代表我撑你。”细微差别是什么？',
    cantoneseText: '我帮你，唔代表我撑你。',
    choices: ['可以帮忙，但不一定认同你', '帮忙就一定完全支持', '我不会提供任何帮助', '我只是想借钱'],
    answerIndex: 0,
    explanation: '“撑你”是支持你、站你这边。帮忙和立场支持被区分开了。',
    theme: '立场切割',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '关系边界',
    pronunciationHint: 'ngo5 bong1 nei5, m4 doi6 biu2 ngo5 caang1 nei5'
  },
  {
    id: 11,
    prompt: '“你今日畀个交代我。”这里“交代”更接近？',
    cantoneseText: '你今日畀个交代我。',
    choices: ['给一个说明或说法', '交一份菜单', '带我去唱歌', '给我一点零钱'],
    answerIndex: 0,
    explanation: '“畀个交代”是要求解释、回应或说法，常带压力。',
    theme: '上门追问',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '常用场面话',
    pronunciationHint: 'nei5 gam1 jat6 bei2 go3 gaau1 doi6 ngo5'
  },
  {
    id: 12,
    prompt: '“你唔好以为笑两声就冇事。”说话人最可能？',
    cantoneseText: '你唔好以为笑两声就冇事。',
    choices: ['不接受对方轻轻带过', '觉得对方笑得很好听', '事情已经完全解决', '想让气氛更轻松'],
    answerIndex: 0,
    explanation: '“就冇事”是就没事了；整句是否定这种轻描淡写。',
    theme: '喜剧变严肃',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '语气转折',
    pronunciationHint: 'nei5 m4 hou2 ji5 wai4 siu3 loeng5 seng1 zau6 mou5 si6'
  },
  {
    id: 13,
    prompt: '“我唔想搞大件事。”最符合哪种意图？',
    cantoneseText: '我唔想搞大件事。',
    choices: ['不想把事情闹大', '想马上报警公开', '想把事做得更大', '觉得事情很开心'],
    answerIndex: 0,
    explanation: '“搞大件事”是把事情闹大、扩大化。这句是在压低冲突。',
    theme: '压住冲突',
    difficulty: '进阶',
    questionType: 'meaning',
    skillTag: '冲突控制',
    pronunciationHint: 'ngo5 m4 soeng2 gaau2 daai6 gin6 si6'
  },
  {
    id: 14,
    prompt: '“你想我点做，你直接讲。”潜台词更像？',
    cantoneseText: '你想我点做，你直接讲。',
    choices: ['别绕了，说清楚你的要求', '我已经知道你想什么', '你不用再讲话', '我只想听赞美'],
    answerIndex: 0,
    explanation: '这句不是不知道，而是要求对方把诉求摊开讲。',
    theme: '谈条件',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '需求澄清',
    pronunciationHint: 'nei5 soeng2 ngo5 dim2 zou6, nei5 zik6 zip3 gong2'
  },
  {
    id: 15,
    prompt: '“我当你系朋友，先同你讲真话。”重点在？',
    cantoneseText: '我当你系朋友，先同你讲真话。',
    choices: ['因为重视关系才直说', '因为讨厌你才讽刺', '只是随便闲聊', '说明两人不是朋友'],
    answerIndex: 0,
    explanation: '“先”在这里表示正因为如此才做某事。真话被包装成关系里的提醒。',
    theme: '朋友直劝',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '关系语气',
    pronunciationHint: 'ngo5 dong3 nei5 hai6 pang4 jau5, sin1 tung4 nei5 gong2 zan1 waa6'
  },
  {
    id: 16,
    prompt: '“你而家系咪玩我？”这句不是普通询问，而是？',
    cantoneseText: '你而家系咪玩我？',
    choices: ['觉得对方在耍自己', '邀请对方一起玩游戏', '确认现在几点', '问对方会不会唱歌'],
    answerIndex: 0,
    explanation: '“玩我”在这里是耍我、拿我开玩笑，带不满或怀疑。',
    theme: '误会爆点',
    difficulty: '进阶',
    questionType: 'tone',
    skillTag: '反问不满',
    pronunciationHint: 'nei5 ji4 gaa1 hai6 mai6 waan2 ngo5'
  },
  {
    id: 17,
    prompt: '“唔好讲到自己咁委屈。”说话人不接受什么？',
    cantoneseText: '唔好讲到自己咁委屈。',
    choices: ['对方把自己说成受害者', '对方说话太客气', '对方愿意承担责任', '对方声音太轻'],
    answerIndex: 0,
    explanation: '“讲到自己咁委屈”是把自己说得很可怜、像受害者。',
    theme: '拆穿委屈',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '态度判断',
    pronunciationHint: 'm4 hou2 gong2 dou3 zi6 gei2 gam3 wai2 wat1'
  },
  {
    id: 18,
    prompt: '“算我求你，畀条路行下。”更自然的意思是？',
    cantoneseText: '算我求你，畀条路行下。',
    choices: ['请求对方留一条生路/余地', '真的问路怎么走', '要求对方一起散步', '表示已经赢了'],
    answerIndex: 0,
    explanation: '“畀条路行下”常是比喻给条路、给个余地，不只是字面走路。',
    theme: '讲数求情',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '比喻理解',
    pronunciationHint: 'syun3 ngo5 kau4 nei5, bei2 tiu4 lou6 haang4 haa5'
  },
  {
    id: 19,
    prompt: '“你要面，我都要交代。”这句话在平衡什么？',
    cantoneseText: '你要面，我都要交代。',
    choices: ['给你面子和我需要说法之间的冲突', '谁更适合唱歌', '两个人都要点餐', '双方都不想见面'],
    answerIndex: 0,
    explanation: '“要面”是要面子，“要交代”是需要说法。两边需求在冲突。',
    theme: '两边都难',
    difficulty: '挑战',
    questionType: 'meaning',
    skillTag: '关系权衡',
    pronunciationHint: 'nei5 jiu3 min6, ngo5 dou1 jiu3 gaau1 doi6'
  },
  {
    id: 20,
    prompt: '“今日我忍你，唔代表次次都忍。”最准确的语气是？',
    cantoneseText: '今日我忍你，唔代表次次都忍。',
    choices: ['警告对方不要得寸进尺', '承诺永远忍让', '轻松开玩笑', '表达完全无所谓'],
    answerIndex: 0,
    explanation: '“唔代表次次都忍”是在划线，意思是这次算了，但不会每次都让。',
    theme: '最后警告',
    difficulty: '挑战',
    questionType: 'tone',
    skillTag: '边界警告',
    pronunciationHint: 'gam1 jat6 ngo5 jan2 nei5, m4 doi6 biu2 ci3 ci3 dou1 jan2'
  }
];
